version: '3.8'
services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=123123
    volumes:
      - ./db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    links:
      - backend
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server:/app
    ports:
      - "9876:9876"
    links:
      - frontend
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:3000
    ports:
      - "3000:3000"
    command: sh -c "npm rebuild esbuild && npm run dev"